package com.codzs.mapper.organization;

import com.codzs.constant.domain.DomainConstants;
import com.codzs.dto.organization.request.DomainRequestDto;
import com.codzs.framework.constant.CommonConstants;
import com.codzs.dto.organization.response.DomainResponseDto;
import com.codzs.entity.domain.Domain;
import org.mapstruct.*;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * MapStruct mapper for embedded Domain sub-objects and DTOs.
 * Handles mapping between embedded Domain objects, request DTOs, and response DTOs
 * with proper data transformations and UTC date handling.
 * 
 * @author Codzs Team
 * @since 1.0
 */
@Mapper(
    componentModel = "spring",
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
    nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS
)
@Component
public interface OrganizationDomainMapper {

    // ========================= CREATE MAPPINGS =========================
    
    /**
     * Maps DomainRequestDto to embedded Domain sub-object.
     * Sets default values for domain creation.
     */
    @Mapping(target = "id", expression = "java(java.util.UUID.randomUUID().toString())")
    @Mapping(target = "isVerified", constant = DomainConstants.DEFAULT_IS_VERIFIED)
    @Mapping(target = "isPrimary", expression = "java(requestDto.getIsPrimary() != null ? requestDto.getIsPrimary() : " + DomainConstants.DEFAULT_IS_PRIMARY + ")")
    @Mapping(target = "verificationToken", ignore = true) // Will be generated by service
    @Mapping(target = "verifiedDate", ignore = true)
    @Mapping(target = "createdDate", expression = "java(java.time.Instant.now())")
    @Mapping(source = "name", target = "name", qualifiedByName = "normalizeDomainName")
    Domain toEntity(DomainRequestDto requestDto);

    /**
     * Post-mapping method to set creation audit fields.
     */
    @AfterMapping
    default void setCreationDefaults(@MappingTarget Domain domain) {
        // Generate verification token
        domain.setVerificationToken(generateVerificationToken());
        
        // Normalize domain name
        if (domain.getName() != null) {
            domain.setName(domain.getName().toLowerCase().trim());
        }
    }

    // ========================= UPDATE MAPPINGS =========================
    
    /**
     * Updates existing embedded Domain sub-object with request data.
     * Preserves verification status and timestamps unless explicitly changing.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "isVerified", ignore = true) // Only updated through verification process
    @Mapping(target = "verificationToken", ignore = true)
    @Mapping(target = "verifiedDate", ignore = true)
    @Mapping(target = "createdDate", ignore = true)
    @Mapping(source = "name", target = "name", qualifiedByName = "normalizeDomainName")
    void updateEntity(@MappingTarget Domain domain, DomainRequestDto requestDto);

    // ========================= RESPONSE MAPPINGS =========================
    
    /**
     * Maps embedded Domain sub-object to DomainResponseDto.
     * Handles UTC date formatting and includes all domain information.
     */
    @Mapping(source = "createdDate", target = "createdDate", dateFormat = CommonConstants.UTC_TIMESTAMP_PATTERN)
    @Mapping(source = "verifiedDate", target = "verifiedDate", dateFormat = CommonConstants.UTC_TIMESTAMP_PATTERN)
    @Named("toResponse")
    DomainResponseDto toResponse(Domain domain);

    /**
     * Maps list of Domain entities to list of response DTOs.
     */
    @IterableMapping(qualifiedByName = "toResponse")
    List<DomainResponseDto> toResponseList(List<Domain> domains);

    // ========================= VERIFICATION MAPPINGS =========================
    
    /**
     * Maps embedded Domain sub-object for verification response.
     * Includes verification status and token information.
     */
    @Mapping(source = "verifiedDate", target = "verifiedDate", dateFormat = CommonConstants.UTC_TIMESTAMP_PATTERN)
    @Mapping(source = "createdDate", target = "createdDate", dateFormat = CommonConstants.UTC_TIMESTAMP_PATTERN)
    @Named("toVerificationResponse")
    DomainResponseDto toVerificationResponse(Domain domain);

    // ========================= UTILITY METHODS =========================
    
    /**
     * Normalizes domain name to lowercase and validates format.
     */
    @Named("normalizeDomainName")
    default String normalizeDomainName(String domainName) {
        if (domainName == null || domainName.trim().isEmpty()) {
            return null;
        }
        
        String normalized = domainName.trim().toLowerCase();
         
        // Basic domain validation - remove protocol if present
        if (normalized.startsWith(CommonConstants.HTTP_PROTOCOL)) {
            normalized = normalized.substring(7);
        } else if (normalized.startsWith(CommonConstants.HTTPS_PROTOCOL)) {
            normalized = normalized.substring(8);
        }
        
        // Remove trailing slash
        if (normalized.endsWith("/")) {
            normalized = normalized.substring(0, normalized.length() - 1);
        }
        
        return normalized;
    }

    /**
     * Generates verification token for domain verification.
     */
    default String generateVerificationToken() {
        return "dom_" + System.currentTimeMillis() + "_" + 
               Integer.toHexString((int) (Math.random() * 0x1000000));
    }

    /**
     * Converts Instant to UTC formatted string.
     */
    default String instantToUtcString(Instant instant) {
        return instant != null ? instant.toString() : null;
    }

    /**
     * Converts UTC formatted string to Instant.
     */
    default Instant utcStringToInstant(String utcString) {
        return utcString != null && !utcString.trim().isEmpty() ? Instant.parse(utcString) : null;
    }
}